version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    container_name: "mongodb-container"
    ports:
      - 27017:27017
    volumes:
      - mainData:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    container_name: "mongoExpress-container"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb-container"
    ports:
      - 8085:8081
volumes:
  mainData:
