version: "3.9"
services:
  mysql:
    container_name: "mysql"
    image: mysql
    restart: always
    volumes:
      - adminData:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  adminData:
